<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Shrivathsas-MacBook-Pro.local" name="com.branch.qa.testcases.TeamPageTest" tests="5" failures="1" timestamp="14 May 2018 07:29:52 GMT" time="9.920" errors="0">
  <testcase name="verifyEmployeeNumberTest" time="9.920" classname="com.branch.qa.testcases.TeamPageTest">
    <failure type="java.lang.AssertionError" message="expected [129] but found [125]">
      <![CDATA[java.lang.AssertionError: expected [129] but found [125]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:652)at org.testng.Assert.assertEquals(Assert.java:662)at com.branch.qa.testcases.TeamPageTest.verifyEmployeeNumberTest(TeamPageTest.java:37)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- verifyEmployeeNumberTest -->
  <testcase name="verifyEmployeeNameTest" classname="com.branch.qa.testcases.TeamPageTest">
    <skipped/>
  </testcase> <!-- verifyEmployeeNameTest -->
  <testcase name="printTeamMemberNamesTest" classname="com.branch.qa.testcases.TeamPageTest">
    <skipped/>
  </testcase> <!-- printTeamMemberNamesTest -->
  <testcase name="verifyTitleTest" classname="com.branch.qa.testcases.TeamPageTest">
    <skipped/>
  </testcase> <!-- verifyTitleTest -->
  <testcase name="verifyEmployeeDeptTest" classname="com.branch.qa.testcases.TeamPageTest">
    <skipped/>
  </testcase> <!-- verifyEmployeeDeptTest -->
</testsuite> <!-- com.branch.qa.testcases.TeamPageTest -->
